### ISSUE TITLE
Anchors on Staff page need adjusting

### ISSUE THREAD

**Issue by tmus** [st-c/web#1]
When you view a member of staff, e.g., `/staff/#tsmith`, the page compensates for the fixed header (as it should), but the image is cut off.

A CSS rule such as:

```css
h2.staff-name[id]:before {
  display:block;
  content:" ";
  height:75px;
  margin-top:-75px;
  visibility:hidden;
}
```

Should suffice, but will implement and test.
